version: '3.8'

services:
  api-gateway:
    build:
      context: ./server/src/microservices/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_GATEWAY_PORT=3000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_secret_key
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server/src/microservices/api-gateway:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongodb

  media-service:
    build:
      context: ./server/src/microservices/media-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CIRCUIT_BREAKER_THRESHOLD=5
      - CIRCUIT_BREAKER_TIMEOUT_MS=30000
      - MAX_WORKERS=2
      - MIN_WORKERS=1
    volumes:
      - ./server/src/microservices/media-service:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      - redis

  analytics-service:
    build:
      context: ./server/src/microservices/analytics-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - ANALYTICS_SERVICE_PORT=3003
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/lumina
    volumes:
      - ./server/src/microservices/analytics-service:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_MEDIA_URL=http://localhost:3000/media
      - VITE_ANALYTICS_URL=http://localhost:3000/analytics
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api-gateway

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lumina

volumes:
  redis-data:
  mongodb-data:
