services:
  - type: web
    name: project-call-server
    env: node
    plan: starter
    buildCommand: cd server && npm ci --only=production && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1536 --optimize-for-size --expose-gc"
      - key: PORT
        value: 8000
      - key: HOST
        value: "0.0.0.0"
      - key: LOG_LEVEL
        value: warn
      - key: LOG_FILE_MAX_SIZE
        value: "5242880"
      - key: LOG_FILE_MAX_FILES
        value: "3"
    healthCheckPath: /health
    autoDeploy: true
    
  - type: web
    name: project-call-client
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
