global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "voice-ai-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["server:3000"]
        labels:
          service: "voice-ai-api"
          environment: "production"

  - job_name: "voice-ai-ml"
    metrics_path: /metrics
    static_configs:
      - targets: ["ml-service:5000"]
        labels:
          service: "voice-ai-ml"
          environment: "production"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          environment: "production"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          environment: "production"

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgres"
          environment: "production"

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "redis"
          environment: "production"
