apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-analytics-service
  namespace: lumina-outreach
  labels:
    app: lumina-outreach
    component: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lumina-outreach
      component: analytics-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lumina-outreach
        component: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: analytics-service
        image: ${REGISTRY}/lumina-analytics-service:${TAG}
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: ANALYTICS_SERVICE_PORT
          value: "3003"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: redis_url
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: mongodb_uri
        # Performance tuning
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        ports:
        - containerPort: 3003
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lumina-analytics-service
  namespace: lumina-outreach
  labels:
    app: lumina-outreach
    component: analytics-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: lumina-outreach
    component: analytics-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lumina-analytics-service-hpa
  namespace: lumina-outreach
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lumina-analytics-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
