apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-media-service
  namespace: lumina-outreach
  labels:
    app: lumina-outreach
    component: media-service
spec:
  replicas: 3  # Increased replicas for better scalability
  selector:
    matchLabels:
      app: lumina-outreach
      component: media-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lumina-outreach
        component: media-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: media-service
        image: ${REGISTRY}/lumina-media-service:${TAG}
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_URL  # Changed to use connection URL for Redis Sentinel support
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: redis_url
        - name: DEEPGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: deepgram_api_key
        - name: ELEVENLABS_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: elevenlabs_api_key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: openai_api_key
        # Added for Circuit Breaker configuration
        - name: CIRCUIT_BREAKER_THRESHOLD
          value: "5"
        - name: CIRCUIT_BREAKER_TIMEOUT_MS
          value: "30000" 
        # Worker pool configuration
        - name: MAX_WORKERS
          value: "4"
        - name: MIN_WORKERS
          value: "2"
        # Performance tuning
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048 --max-http-header-size=16384"
        ports:
        - containerPort: 3002
          name: http
        - containerPort: 8080
          name: ws
        resources:
          requests:
            cpu: 1000m  # Increased CPU request
            memory: 1Gi  # Increased memory request
          limits:
            cpu: 3      # Increased CPU limit
            memory: 3Gi  # Increased memory limit
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: audio-cache
          mountPath: /app/audio-cache
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: audio-cache
        persistentVolumeClaim:
          claimName: audio-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lumina-media-service
  namespace: lumina-outreach
  labels:
    app: lumina-outreach
    component: media-service
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: ws
  selector:
    app: lumina-outreach
    component: media-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lumina-media-service-hpa
  namespace: lumina-outreach
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lumina-media-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-cache-pvc
  namespace: lumina-outreach
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
